version: '3.8'

services:
  # Backend API Server
  backend:
    build: ./backend
    container_name: arbitrage-backend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DEMO_MODE=false
    networks:
      - arbitrage-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Frontend Dashboard
  frontend:
    build: ./frontend
    container_name: arbitrage-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - arbitrage-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Ultra-Fast Arbitrage Engine (optional - for advanced users)
  # Uncomment to run the arbitrage engine in production mode
  # arbitrage-engine:
  #   build: ./ultra-fast-arbitrage-engine
  #   container_name: arbitrage-engine
  #   depends_on:
  #     - backend
  #   networks:
  #     - arbitrage-network
  #   restart: unless-stopped

networks:
  arbitrage-network:
    driver: bridge
